services:
  - type: web
    name: finexo-api
    env: python
    rootDir: apps/api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
